// Generated by Scripts/generate_app_server_v2.py.
// Do not edit manually.

import Foundation

extension AppServerV2 {
    public struct AbsolutePathBuf: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Account: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AccountLoginCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AccountRateLimitsUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AccountUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AgentMessageDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AgentPath: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AnalyticsConfig: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppBranding: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppConfig: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppInfo: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppListUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppMetadata: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppReview: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppScreenshot: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppSummary: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppToolApproval: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppToolConfig: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppToolsConfig: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppsConfig: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppsDefaultConfig: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppsListParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AppsListResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct AuthMode: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ByteRange: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CancelLoginAccountParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CancelLoginAccountResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CancelLoginAccountStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ClientInfo: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ClientRequest: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CodexErrorInfo: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CollabAgentState: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CollabAgentStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CollabAgentTool: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CollabAgentToolCallStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CollaborationMode: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CollaborationModeMask: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandAction: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecOutputDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecOutputStream: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecResizeParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecResizeResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecTerminalSize: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecTerminateParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecTerminateResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecWriteParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecWriteResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecutionOutputDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecutionSource: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CommandExecutionStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Config: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigBatchWriteParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigEdit: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigLayer: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigLayerMetadata: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigLayerSource: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigReadParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigReadResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigRequirements: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigRequirementsReadResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigValueWriteParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigWarningNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ConfigWriteResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ContentItem: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ContextCompactedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct CreditsSnapshot: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct DeprecationNoticeNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct DynamicToolCallOutputContentItem: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct DynamicToolCallStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct DynamicToolSpec: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ErrorNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExperimentalFeature: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExperimentalFeatureListParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExperimentalFeatureListResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExperimentalFeatureStage: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExternalAgentConfigDetectParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExternalAgentConfigDetectResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExternalAgentConfigImportParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExternalAgentConfigImportResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExternalAgentConfigMigrationItem: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ExternalAgentConfigMigrationItemType: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FeedbackUploadParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FeedbackUploadResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FileChangeOutputDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FileUpdateChange: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ForcedLoginMethod: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsCopyParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsCopyResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsCreateDirectoryParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsCreateDirectoryResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsGetMetadataParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsGetMetadataResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsReadDirectoryEntry: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsReadDirectoryParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsReadDirectoryResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsReadFileParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsReadFileResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsRemoveParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsRemoveResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsWriteFileParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FsWriteFileResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FunctionCallOutputBody: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FunctionCallOutputContentItem: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FuzzyFileSearchMatchType: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FuzzyFileSearchParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FuzzyFileSearchResult: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FuzzyFileSearchSessionCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct FuzzyFileSearchSessionUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GetAccountParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GetAccountRateLimitsResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GetAccountResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GhostCommit: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GitInfo: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GuardianApprovalReview: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GuardianApprovalReviewStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct GuardianRiskLevel: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookEventName: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookExecutionMode: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookHandlerType: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookOutputEntry: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookOutputEntryKind: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookPromptFragment: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookRunStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookRunSummary: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookScope: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct HookStartedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ImageDetail: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct InitializeCapabilities: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct InitializeParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct InitializeResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct InputModality: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ItemCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ItemGuardianApprovalReviewCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ItemGuardianApprovalReviewStartedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ItemStartedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ListMcpServerStatusParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ListMcpServerStatusResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct LocalShellAction: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct LocalShellStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct LoginAccountParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct LoginAccountResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct LogoutAccountResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct MarketplaceInterface: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpAuthStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpServerOauthLoginCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpServerOauthLoginParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpServerOauthLoginResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpServerRefreshResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpServerStartupState: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpServerStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpServerStatusUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpToolCallError: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpToolCallProgressNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpToolCallResult: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct McpToolCallStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct MemoryCitation: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct MemoryCitationEntry: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct MergeStrategy: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct MessagePhase: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ModeKind: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Model: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ModelAvailabilityNux: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ModelListParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ModelListResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ModelRerouteReason: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ModelReroutedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ModelUpgradeInfo: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct NetworkAccess: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct NetworkRequirements: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct NonSteerableTurnKind: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct OverriddenMetadata: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PatchApplyStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PatchChangeKind: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PlanDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginAuthPolicy: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginDetail: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginInstallParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginInstallPolicy: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginInstallResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginInterface: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginListParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginListResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginMarketplaceEntry: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginReadParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginReadResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginSource: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginSummary: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginUninstallParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct PluginUninstallResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ProfileV2: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct RateLimitSnapshot: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct RateLimitWindow: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct RawResponseItemCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReadOnlyAccess: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct RealtimeConversationVersion: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReasoningEffortOption: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReasoningItemContent: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReasoningItemReasoningSummary: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReasoningSummaryPartAddedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReasoningSummaryTextDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReasoningTextDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct RequestId: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ResidencyRequirement: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Resource: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ResourceTemplate: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ResponseItem: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ResponsesApiWebSearchAction: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReviewDelivery: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReviewStartParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReviewStartResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ReviewTarget: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SandboxWorkspaceWrite: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ServerInfo: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ServerNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ServerRequestResolvedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SessionSource: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Settings: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillDependencies: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillErrorInfo: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillInterface: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillMetadata: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillScope: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillSummary: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillToolDependency: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillsChangedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillsConfigWriteParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillsConfigWriteResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillsListEntry: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillsListExtraRootsForCwd: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillsListParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SkillsListResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct SubAgentSource: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TerminalInteractionNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TextElement: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TextPosition: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TextRange: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Thread: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadActiveFlag: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadArchiveParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadArchiveResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadArchivedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadClosedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadCompactStartParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadCompactStartResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadForkParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadForkResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadId: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadItem: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadListParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadListResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadLoadedListParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadLoadedListResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadMetadataGitInfoUpdateParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadMetadataUpdateParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadMetadataUpdateResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadNameUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadReadParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadReadResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRealtimeAudioChunk: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRealtimeClosedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRealtimeErrorNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRealtimeItemAddedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRealtimeOutputAudioDeltaNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRealtimeStartedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRealtimeTranscriptUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadResumeParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadResumeResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRollbackParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadRollbackResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadSetNameParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadSetNameResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadShellCommandParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadShellCommandResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadStartParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadStartResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadStartedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadStatusChangedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadTokenUsage: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadTokenUsageUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadUnarchiveParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadUnarchiveResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadUnarchivedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadUnsubscribeParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadUnsubscribeResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ThreadUnsubscribeStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TokenUsageBreakdown: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Tool: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct ToolsV2: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Turn: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnDiffUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnError: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnInterruptParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnInterruptResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnPlanStep: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnPlanStepStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnPlanUpdatedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnStartParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnStartResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnStartedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnSteerParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct TurnSteerResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct UserInput: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct Verbosity: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WebSearchAction: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WebSearchContextSize: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WebSearchLocation: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WebSearchMode: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WebSearchToolConfig: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WindowsSandboxSetupCompletedNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WindowsSandboxSetupMode: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WindowsSandboxSetupStartParams: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WindowsSandboxSetupStartResponse: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WindowsWorldWritableWarningNotification: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

extension AppServerV2 {
    public struct WriteStatus: AppServerV2ValueModel {
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {
            self.jsonValue = jsonValue
        }
    }
}

public enum AppServerNotificationPayload: Sendable, Hashable, Codable {
    case accountLoginCompleted(AppServerV2.AccountLoginCompletedNotification)
    case accountRateLimitsUpdated(AppServerV2.AccountRateLimitsUpdatedNotification)
    case accountUpdated(AppServerV2.AccountUpdatedNotification)
    case appListUpdated(AppServerV2.AppListUpdatedNotification)
    case commandExecOutputDelta(AppServerV2.CommandExecOutputDeltaNotification)
    case configWarning(AppServerV2.ConfigWarningNotification)
    case deprecationNotice(AppServerV2.DeprecationNoticeNotification)
    case error(AppServerV2.ErrorNotification)
    case fuzzyFileSearchSessionCompleted(AppServerV2.FuzzyFileSearchSessionCompletedNotification)
    case fuzzyFileSearchSessionUpdated(AppServerV2.FuzzyFileSearchSessionUpdatedNotification)
    case hookCompleted(AppServerV2.HookCompletedNotification)
    case hookStarted(AppServerV2.HookStartedNotification)
    case agentMessageDelta(AppServerV2.AgentMessageDeltaNotification)
    case itemGuardianApprovalReviewCompleted(AppServerV2.ItemGuardianApprovalReviewCompletedNotification)
    case itemGuardianApprovalReviewStarted(AppServerV2.ItemGuardianApprovalReviewStartedNotification)
    case commandExecutionOutputDelta(AppServerV2.CommandExecutionOutputDeltaNotification)
    case terminalInteraction(AppServerV2.TerminalInteractionNotification)
    case itemCompleted(AppServerV2.ItemCompletedNotification)
    case fileChangeOutputDelta(AppServerV2.FileChangeOutputDeltaNotification)
    case mcpToolCallProgress(AppServerV2.McpToolCallProgressNotification)
    case planDelta(AppServerV2.PlanDeltaNotification)
    case reasoningSummaryPartAdded(AppServerV2.ReasoningSummaryPartAddedNotification)
    case reasoningSummaryTextDelta(AppServerV2.ReasoningSummaryTextDeltaNotification)
    case reasoningTextDelta(AppServerV2.ReasoningTextDeltaNotification)
    case itemStarted(AppServerV2.ItemStartedNotification)
    case mcpServerOauthLoginCompleted(AppServerV2.McpServerOauthLoginCompletedNotification)
    case modelRerouted(AppServerV2.ModelReroutedNotification)
    case serverRequestResolved(AppServerV2.ServerRequestResolvedNotification)
    case skillsChanged(AppServerV2.SkillsChangedNotification)
    case threadArchived(AppServerV2.ThreadArchivedNotification)
    case threadClosed(AppServerV2.ThreadClosedNotification)
    case contextCompacted(AppServerV2.ContextCompactedNotification)
    case threadNameUpdated(AppServerV2.ThreadNameUpdatedNotification)
    case threadRealtimeClosed(AppServerV2.ThreadRealtimeClosedNotification)
    case threadRealtimeError(AppServerV2.ThreadRealtimeErrorNotification)
    case threadRealtimeItemAdded(AppServerV2.ThreadRealtimeItemAddedNotification)
    case threadRealtimeOutputAudioDelta(AppServerV2.ThreadRealtimeOutputAudioDeltaNotification)
    case threadRealtimeStarted(AppServerV2.ThreadRealtimeStartedNotification)
    case threadStarted(AppServerV2.ThreadStartedNotification)
    case threadStatusChanged(AppServerV2.ThreadStatusChangedNotification)
    case threadTokenUsageUpdated(AppServerV2.ThreadTokenUsageUpdatedNotification)
    case threadUnarchived(AppServerV2.ThreadUnarchivedNotification)
    case turnCompleted(AppServerV2.TurnCompletedNotification)
    case turnDiffUpdated(AppServerV2.TurnDiffUpdatedNotification)
    case turnPlanUpdated(AppServerV2.TurnPlanUpdatedNotification)
    case turnStarted(AppServerV2.TurnStartedNotification)
    case windowsWorldWritableWarning(AppServerV2.WindowsWorldWritableWarningNotification)
    case windowsSandboxSetupCompleted(AppServerV2.WindowsSandboxSetupCompletedNotification)
    case unknown(JSONValue)

    init(method: String, params: JSONValue) {
        switch method {
        case "account/login/completed": self = .accountLoginCompleted(AppServerV2.AccountLoginCompletedNotification(jsonValue: params))
        case "account/rateLimits/updated": self = .accountRateLimitsUpdated(AppServerV2.AccountRateLimitsUpdatedNotification(jsonValue: params))
        case "account/updated": self = .accountUpdated(AppServerV2.AccountUpdatedNotification(jsonValue: params))
        case "app/list/updated": self = .appListUpdated(AppServerV2.AppListUpdatedNotification(jsonValue: params))
        case "command/exec/outputDelta": self = .commandExecOutputDelta(AppServerV2.CommandExecOutputDeltaNotification(jsonValue: params))
        case "configWarning": self = .configWarning(AppServerV2.ConfigWarningNotification(jsonValue: params))
        case "deprecationNotice": self = .deprecationNotice(AppServerV2.DeprecationNoticeNotification(jsonValue: params))
        case "error": self = .error(AppServerV2.ErrorNotification(jsonValue: params))
        case "fuzzyFileSearch/sessionCompleted": self = .fuzzyFileSearchSessionCompleted(AppServerV2.FuzzyFileSearchSessionCompletedNotification(jsonValue: params))
        case "fuzzyFileSearch/sessionUpdated": self = .fuzzyFileSearchSessionUpdated(AppServerV2.FuzzyFileSearchSessionUpdatedNotification(jsonValue: params))
        case "hook/completed": self = .hookCompleted(AppServerV2.HookCompletedNotification(jsonValue: params))
        case "hook/started": self = .hookStarted(AppServerV2.HookStartedNotification(jsonValue: params))
        case "item/agentMessage/delta": self = .agentMessageDelta(AppServerV2.AgentMessageDeltaNotification(jsonValue: params))
        case "item/autoApprovalReview/completed": self = .itemGuardianApprovalReviewCompleted(AppServerV2.ItemGuardianApprovalReviewCompletedNotification(jsonValue: params))
        case "item/autoApprovalReview/started": self = .itemGuardianApprovalReviewStarted(AppServerV2.ItemGuardianApprovalReviewStartedNotification(jsonValue: params))
        case "item/commandExecution/outputDelta": self = .commandExecutionOutputDelta(AppServerV2.CommandExecutionOutputDeltaNotification(jsonValue: params))
        case "item/commandExecution/terminalInteraction": self = .terminalInteraction(AppServerV2.TerminalInteractionNotification(jsonValue: params))
        case "item/completed": self = .itemCompleted(AppServerV2.ItemCompletedNotification(jsonValue: params))
        case "item/fileChange/outputDelta": self = .fileChangeOutputDelta(AppServerV2.FileChangeOutputDeltaNotification(jsonValue: params))
        case "item/mcpToolCall/progress": self = .mcpToolCallProgress(AppServerV2.McpToolCallProgressNotification(jsonValue: params))
        case "item/plan/delta": self = .planDelta(AppServerV2.PlanDeltaNotification(jsonValue: params))
        case "item/reasoning/summaryPartAdded": self = .reasoningSummaryPartAdded(AppServerV2.ReasoningSummaryPartAddedNotification(jsonValue: params))
        case "item/reasoning/summaryTextDelta": self = .reasoningSummaryTextDelta(AppServerV2.ReasoningSummaryTextDeltaNotification(jsonValue: params))
        case "item/reasoning/textDelta": self = .reasoningTextDelta(AppServerV2.ReasoningTextDeltaNotification(jsonValue: params))
        case "item/started": self = .itemStarted(AppServerV2.ItemStartedNotification(jsonValue: params))
        case "mcpServer/oauthLogin/completed": self = .mcpServerOauthLoginCompleted(AppServerV2.McpServerOauthLoginCompletedNotification(jsonValue: params))
        case "model/rerouted": self = .modelRerouted(AppServerV2.ModelReroutedNotification(jsonValue: params))
        case "serverRequest/resolved": self = .serverRequestResolved(AppServerV2.ServerRequestResolvedNotification(jsonValue: params))
        case "skills/changed": self = .skillsChanged(AppServerV2.SkillsChangedNotification(jsonValue: params))
        case "thread/archived": self = .threadArchived(AppServerV2.ThreadArchivedNotification(jsonValue: params))
        case "thread/closed": self = .threadClosed(AppServerV2.ThreadClosedNotification(jsonValue: params))
        case "thread/compacted": self = .contextCompacted(AppServerV2.ContextCompactedNotification(jsonValue: params))
        case "thread/name/updated": self = .threadNameUpdated(AppServerV2.ThreadNameUpdatedNotification(jsonValue: params))
        case "thread/realtime/closed": self = .threadRealtimeClosed(AppServerV2.ThreadRealtimeClosedNotification(jsonValue: params))
        case "thread/realtime/error": self = .threadRealtimeError(AppServerV2.ThreadRealtimeErrorNotification(jsonValue: params))
        case "thread/realtime/itemAdded": self = .threadRealtimeItemAdded(AppServerV2.ThreadRealtimeItemAddedNotification(jsonValue: params))
        case "thread/realtime/outputAudio/delta": self = .threadRealtimeOutputAudioDelta(AppServerV2.ThreadRealtimeOutputAudioDeltaNotification(jsonValue: params))
        case "thread/realtime/started": self = .threadRealtimeStarted(AppServerV2.ThreadRealtimeStartedNotification(jsonValue: params))
        case "thread/started": self = .threadStarted(AppServerV2.ThreadStartedNotification(jsonValue: params))
        case "thread/status/changed": self = .threadStatusChanged(AppServerV2.ThreadStatusChangedNotification(jsonValue: params))
        case "thread/tokenUsage/updated": self = .threadTokenUsageUpdated(AppServerV2.ThreadTokenUsageUpdatedNotification(jsonValue: params))
        case "thread/unarchived": self = .threadUnarchived(AppServerV2.ThreadUnarchivedNotification(jsonValue: params))
        case "turn/completed": self = .turnCompleted(AppServerV2.TurnCompletedNotification(jsonValue: params))
        case "turn/diff/updated": self = .turnDiffUpdated(AppServerV2.TurnDiffUpdatedNotification(jsonValue: params))
        case "turn/plan/updated": self = .turnPlanUpdated(AppServerV2.TurnPlanUpdatedNotification(jsonValue: params))
        case "turn/started": self = .turnStarted(AppServerV2.TurnStartedNotification(jsonValue: params))
        case "windows/worldWritableWarning": self = .windowsWorldWritableWarning(AppServerV2.WindowsWorldWritableWarningNotification(jsonValue: params))
        case "windowsSandbox/setupCompleted": self = .windowsSandboxSetupCompleted(AppServerV2.WindowsSandboxSetupCompletedNotification(jsonValue: params))
        default:
            self = .unknown(params)
        }
    }

    var rawValue: JSONValue {
        switch self {
        case .accountLoginCompleted(let value): return value.jsonValue
        case .accountRateLimitsUpdated(let value): return value.jsonValue
        case .accountUpdated(let value): return value.jsonValue
        case .appListUpdated(let value): return value.jsonValue
        case .commandExecOutputDelta(let value): return value.jsonValue
        case .configWarning(let value): return value.jsonValue
        case .deprecationNotice(let value): return value.jsonValue
        case .error(let value): return value.jsonValue
        case .fuzzyFileSearchSessionCompleted(let value): return value.jsonValue
        case .fuzzyFileSearchSessionUpdated(let value): return value.jsonValue
        case .hookCompleted(let value): return value.jsonValue
        case .hookStarted(let value): return value.jsonValue
        case .agentMessageDelta(let value): return value.jsonValue
        case .itemGuardianApprovalReviewCompleted(let value): return value.jsonValue
        case .itemGuardianApprovalReviewStarted(let value): return value.jsonValue
        case .commandExecutionOutputDelta(let value): return value.jsonValue
        case .terminalInteraction(let value): return value.jsonValue
        case .itemCompleted(let value): return value.jsonValue
        case .fileChangeOutputDelta(let value): return value.jsonValue
        case .mcpToolCallProgress(let value): return value.jsonValue
        case .planDelta(let value): return value.jsonValue
        case .reasoningSummaryPartAdded(let value): return value.jsonValue
        case .reasoningSummaryTextDelta(let value): return value.jsonValue
        case .reasoningTextDelta(let value): return value.jsonValue
        case .itemStarted(let value): return value.jsonValue
        case .mcpServerOauthLoginCompleted(let value): return value.jsonValue
        case .modelRerouted(let value): return value.jsonValue
        case .serverRequestResolved(let value): return value.jsonValue
        case .skillsChanged(let value): return value.jsonValue
        case .threadArchived(let value): return value.jsonValue
        case .threadClosed(let value): return value.jsonValue
        case .contextCompacted(let value): return value.jsonValue
        case .threadNameUpdated(let value): return value.jsonValue
        case .threadRealtimeClosed(let value): return value.jsonValue
        case .threadRealtimeError(let value): return value.jsonValue
        case .threadRealtimeItemAdded(let value): return value.jsonValue
        case .threadRealtimeOutputAudioDelta(let value): return value.jsonValue
        case .threadRealtimeStarted(let value): return value.jsonValue
        case .threadStarted(let value): return value.jsonValue
        case .threadStatusChanged(let value): return value.jsonValue
        case .threadTokenUsageUpdated(let value): return value.jsonValue
        case .threadUnarchived(let value): return value.jsonValue
        case .turnCompleted(let value): return value.jsonValue
        case .turnDiffUpdated(let value): return value.jsonValue
        case .turnPlanUpdated(let value): return value.jsonValue
        case .turnStarted(let value): return value.jsonValue
        case .windowsWorldWritableWarning(let value): return value.jsonValue
        case .windowsSandboxSetupCompleted(let value): return value.jsonValue
        case .unknown(let value):
            return value
        }
    }
}

