#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "vendor" / "openai-codex" / "sdk" / "python" / "src" / "codex_app_server" / "generated" / "notification_registry.py"
SCHEMA_PATH = REPO_ROOT / "vendor" / "openai-codex" / "codex-rs" / "app-server-protocol" / "schema" / "json" / "codex_app_server_protocol.v2.schemas.json"
OUTPUT_PATH = REPO_ROOT / "Sources" / "Codex" / "AppServerV2Generated.swift"

MANUAL_TYPES = {
    "ApprovalMode",
    "ApprovalsReviewer",
    "AskForApproval",
    "Personality",
    "PlanType",
    "ReasoningEffort",
    "ReasoningSummary",
    "SandboxMode",
    "SandboxPolicy",
    "ServiceTier",
    "ThreadSortKey",
    "ThreadSourceKind",
    "TurnStatus",
}

EXTRA_TYPES = [
    "InitializeResponse",
    "ServerInfo",
    "ModelListResponse",
    "Thread",
    "ThreadArchiveResponse",
    "ThreadCompactStartResponse",
    "ThreadForkResponse",
    "ThreadListResponse",
    "ThreadReadResponse",
    "ThreadResumeResponse",
    "ThreadSetNameResponse",
    "ThreadStartResponse",
    "ThreadUnarchiveResponse",
    "ThreadTokenUsage",
    "Turn",
    "TurnError",
    "TurnInterruptResponse",
    "TurnStartResponse",
    "TurnSteerResponse",
    "ThreadItem",
]


def lower_camel(value: str) -> str:
    return value[:1].lower() + value[1:]


def read_notification_registry() -> tuple[list[str], list[tuple[str, str]]]:
    text = REGISTRY_PATH.read_text()
    imported = re.findall(r"from \.v2_all import (\w+)", text)
    mapping = re.findall(r'"([^"]+)": (\w+),', text)
    return imported, mapping


def read_schema_type_names() -> list[str]:
    schema = json.loads(SCHEMA_PATH.read_text())
    definitions = schema.get("definitions", {})
    names: list[str] = []
    for name in definitions:
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            continue
        if name in MANUAL_TYPES:
            continue
        names.append(name)
    return names


def emit_wrapper(name: str) -> str:
    return f"""extension AppServerV2 {{
    public struct {name}: AppServerV2ValueModel {{
        public var jsonValue: JSONValue

        public init(jsonValue: JSONValue) {{
            self.jsonValue = jsonValue
        }}
    }}
}}
"""


def emit_payload_enum(mapping: list[tuple[str, str]]) -> str:
    cases: list[str] = []
    init_cases: list[str] = []
    raw_cases: list[str] = []

    for method, class_name in mapping:
        base_name = class_name[:-12] if class_name.endswith("Notification") else class_name
        case_name = lower_camel(base_name)
        cases.append(f"    case {case_name}(AppServerV2.{class_name})")
        init_cases.append(
            f'        case "{method}": self = .{case_name}(AppServerV2.{class_name}(jsonValue: params))'
        )
        raw_cases.append(f"        case .{case_name}(let value): return value.jsonValue")

    return """public enum AppServerNotificationPayload: Sendable, Hashable, Codable {
""" + "\n".join(cases) + """
    case unknown(JSONValue)

    init(method: String, params: JSONValue) {
        switch method {
""" + "\n".join(init_cases) + """
        default:
            self = .unknown(params)
        }
    }

    var rawValue: JSONValue {
        switch self {
""" + "\n".join(raw_cases) + """
        case .unknown(let value):
            return value
        }
    }
}
"""


def main() -> None:
    imported, mapping = read_notification_registry()
    schema_types = read_schema_type_names()
    all_types = sorted(set(imported + schema_types + EXTRA_TYPES))
    wrappers = "\n".join(emit_wrapper(name) for name in all_types)
    payload_enum = emit_payload_enum(mapping)

    output = f"""// Generated by Scripts/generate_app_server_v2.py.
// Do not edit manually.

import Foundation

{wrappers}
{payload_enum}
"""

    OUTPUT_PATH.write_text(output)


if __name__ == "__main__":
    main()
